[[contracts]]
fqn = "dex_contracts::unified_dex::UnifiedDex"

[[contracts]]
fqn = "dex_contracts::unified_position_manager::UnifiedPositionManager"

[[contracts]]
fqn = "dex_contracts::test_token::TestToken"

[[contracts]]
fqn = "dex_contracts::router::Router"